
import React, { useState, useEffect } from 'react';
import { performMycoAnalysis } from './services/geminiService';
import { AnalysisResult, Haplotype } from './types';
import { StrainMap } from './components/StrainMap';
import { NetworkGraph } from './components/NetworkGraph';
import { 
  Dna, Search, Loader2, AlertCircle, Download, Target, Globe, FileText, Link, Scale, Activity, ChevronDown, Sparkles, Key, ShieldCheck, LogOut, Info, Shield, ExternalLink, HelpCircle, ArrowRight, AlertTriangle, CheckCircle2, ChevronRight, Zap, RefreshCw, Layers, Bug
} from 'lucide-react';

const FOCUS_OPTIONS = ["National Survey", "Pacific Northwest (PNW)", "Appalachian Mountains", "Northeast Deciduous", "Southeast Coastal Plain", "Rocky Mountains / Alpine", "California Floristic", "Boreal Forest / Taiga"];
const APP_VERSION = "v2.5";

export default function App() {
  const [species, setSpecies] = useState('');
  const [focusArea, setFocusArea] = useState(FOCUS_OPTIONS[0]);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [showAuthModal, setShowAuthModal] = useState(false);
  const [isAuthorized, setIsAuthorized] = useState(false);
  const [envStatus, setEnvStatus] = useState<'checking' | 'bridge' | 'standalone'>('checking');
  const [showTroubleshooting, setShowTroubleshooting] = useState(false);

  useEffect(() => {
    let attempts = 0;
    const maxAttempts = 15; 

    const checkEnv = async () => {
      if (window.aistudio && typeof window.aistudio.hasSelectedApiKey === 'function') {
        setEnvStatus('bridge');
        const authed = await window.aistudio.hasSelectedApiKey();
        setIsAuthorized(authed);
        return true;
      }
      if (process.env.API_KEY) {
        setEnvStatus('standalone');
        setIsAuthorized(true);
        return true;
      }
      return false;
    };

    const interval = setInterval(async () => {
      attempts++;
      const found = await checkEnv();
      if (found || attempts >= maxAttempts) {
        if (!found) setEnvStatus('standalone'); 
        clearInterval(interval);
      }
    }, 500);

    checkEnv();
    return () => clearInterval(interval);
  }, []);

  const handleAuth = () => {
    if (envStatus !== 'bridge') {
      setError("Handshake Unavailable: This button requires the Google AI Studio environment.");
      return;
    }
    try {
      if (window.aistudio?.openSelectKey) {
        window.aistudio.openSelectKey();
        setIsAuthorized(true);
        setShowAuthModal(false);
        setError(null);
      }
    } catch (err) {
      console.error("Bridge call failed:", err);
      setError("Authorization blocked. Please allow popups.");
    }
  };

  const handleSearch = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!species.trim()) return;

    setLoading(true);
    setError(null);
    try {
      const data = await performMycoAnalysis(species, focusArea);
      setResult(data);
    } catch (err: any) {
      if (err.message?.includes("Requested entity was not found") || err.message === "MISSING_KEY") {
        setIsAuthorized(false);
        setShowAuthModal(true);
        setError("Your Google project requires active billing for 'Pro' features.");
      } else {
        setError(err.message || "An unexpected error occurred.");
      }
    } finally {
      setLoading(false);
    }
  };

  const formatHaplotypeData = (haplotypes: Haplotype[]) => {
    return haplotypes.map(h => {
      return `ID: ${h.id}
Region: ${h.region}
Similarity: ${h.similarity}%
Host Association: ${h.substrate}
Chemistry: ${h.chemistry}
Insect Associations: ${h.insectAssociations}
SNPs: ${h.snps.join(', ')}
Coordinates: [${h.lat}, ${h.lng}]
`;
    }).join('\n');
  };

  const handleExportDossier = () => {
    if (!result) return;
    const formattedHaplotypes = formatHaplotypeData(result.haplotypes);
    const fullContent = `
MYCOSTRAIN EXPLORER: GENOMIC & ENTOMOLOGICAL REPORT
====================================================
Species: ${result.speciesName}
Focus Area: ${result.focusArea}
Nucleotide Diversity (π): ${result.nucleotideDiversity}
Estimated Regional Haplotypes: ${result.estimatedTotalHaplotypes}
Estimated Global Haplotypes: ${result.estimatedGlobalHaplotypes}

RESEARCH SUMMARY
----------------
${result.dossier}

HAPLOTYPE DATA
--------------
${formattedHaplotypes}
----------------
Generated by MycoStrain Explorer ${APP_VERSION}
    `.trim();

    const blob = new Blob([fullContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `MycoStrain_${result.speciesName.replace(/\s/g, '_')}_Dossier_v2.5.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col font-sans">
      {/* Auth Modal */}
      {showAuthModal && (
        <div className="fixed inset-0 z-[100] bg-slate-900/95 backdrop-blur-xl flex items-center justify-center p-4">
          <div className="bg-white rounded-[3rem] p-8 md:p-12 max-w-2xl w-full shadow-2xl border border-slate-200 overflow-y-auto max-h-[90vh] custom-scrollbar">
            <header className="mb-10 text-center">
              <div className="bg-indigo-600 w-16 h-16 rounded-2xl text-white shadow-xl flex items-center justify-center mx-auto mb-6">
                <Shield size={32} />
              </div>
              <h3 className="text-3xl font-black text-slate-900 tracking-tight">System Authorization {APP_VERSION}</h3>
              <p className="text-slate-400 text-xs font-bold uppercase tracking-widest mt-2">Secure Handshake Protocol</p>
            </header>
            <div className="space-y-4 mb-10">
              {envStatus === 'standalone' && !process.env.API_KEY && (
                <div className="bg-amber-50 border border-amber-200 p-6 rounded-3xl flex gap-4 mb-6 animate-in slide-in-from-top-2">
                  <AlertCircle className="text-amber-600 shrink-0" size={24} />
                  <div>
                    <h4 className="text-[11px] font-black text-amber-900 uppercase tracking-widest mb-1">Standalone Mode (Vercel)</h4>
                    <p className="text-[12px] text-amber-800 leading-relaxed">
                      Bridge handshake only works when run inside Google AI Studio.
                    </p>
                  </div>
                </div>
              )}
              <div className="bg-indigo-600 text-white p-6 rounded-3xl shadow-xl shadow-indigo-200 relative overflow-hidden group">
                <Sparkles className="absolute top-0 right-0 text-white/10 -mt-4 -mr-4" size={80} />
                <div className="flex items-start gap-4 relative z-10">
                  <div className="bg-white/20 text-white w-8 h-8 rounded-full flex items-center justify-center font-black shrink-0">3</div>
                  <div className="flex-1">
                    <h4 className="text-sm font-black uppercase tracking-tight mb-1">Cloud Handshake</h4>
                    <button 
                      onClick={handleAuth} 
                      disabled={envStatus !== 'bridge'}
                      className={`w-full py-4 rounded-2xl font-black flex items-center justify-center gap-3 mt-4 transition-all ${
                        envStatus === 'bridge' 
                        ? 'bg-white text-indigo-600 hover:bg-slate-50' 
                        : 'bg-indigo-500 text-indigo-200 cursor-not-allowed'
                      }`}
                    >
                      {envStatus === 'bridge' ? 'LINK GOOGLE PROJECT' : 'DISABLED ON VERCEL'}
                    </button>
                  </div>
                </div>
              </div>
            </div>
            <button onClick={() => setShowAuthModal(false)} className="w-full text-center text-[10px] font-black text-slate-300 hover:text-slate-400 uppercase tracking-widest">DISMISS</button>
          </div>
        </div>
      )}

      <nav className="bg-white/80 backdrop-blur-md border-b border-slate-200 sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="bg-indigo-600 p-2.5 rounded-xl text-white shadow-lg"><Dna size={24} /></div>
            <div className="flex flex-col">
              <div className="flex items-center gap-2">
                <h1 className="text-xl font-black text-slate-900 tracking-tight leading-none">MycoStrain <span className="text-indigo-600">Explorer</span></h1>
                <span className="px-2 py-0.5 bg-slate-100 border border-slate-200 text-slate-500 rounded-md text-[9px] font-black uppercase tracking-tighter">{APP_VERSION}</span>
              </div>
              <p className="text-[9px] font-black text-slate-400 uppercase tracking-[0.2em] mt-1">Bioinformatics & Entomology</p>
            </div>
          </div>
          <div className="flex items-center gap-6">
            {isAuthorized ? (
              <div className="flex items-center gap-4">
                <div className="flex items-center gap-2 px-4 py-2 bg-green-50 border border-green-100 rounded-full text-[10px] font-black text-green-700 uppercase tracking-widest">
                  <ShieldCheck size={14} /> Session Verified
                </div>
              </div>
            ) : (
              <button onClick={() => setShowAuthModal(true)} className="flex items-center gap-2 px-6 py-2.5 bg-indigo-600 text-white rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-indigo-700 transition-all">
                <HelpCircle size={14} /> Setup Access
              </button>
            )}
          </div>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto px-6 py-10 flex-grow w-full">
        <section className="mb-12 text-center max-w-4xl mx-auto">
          <h2 className="text-5xl font-black text-slate-900 mb-4 tracking-tighter">Genomic & Entomological Modeling</h2>
          <p className="text-slate-500 text-lg font-medium leading-relaxed mb-10">Tracing genetic drift and insect-fungal symbioses.</p>
          <div className="bg-white p-4 rounded-[2.5rem] shadow-2xl border border-slate-200/60 ring-8 ring-slate-100/50">
            <form onSubmit={handleSearch} className="flex flex-col lg:flex-row gap-4">
              <input 
                type="text" 
                value={species} 
                onChange={(e) => setSpecies(e.target.value)} 
                placeholder="Scientific Name (e.g. Cyathus striatus)" 
                className="flex-[1.5] pl-10 pr-6 py-6 rounded-3xl bg-slate-50 border-none focus:ring-2 focus:ring-indigo-500 outline-none font-bold text-slate-800 shadow-inner" 
              />
              <select 
                value={focusArea} 
                onChange={(e) => setFocusArea(e.target.value)} 
                className="flex-1 px-10 py-6 rounded-3xl bg-slate-50 border-none focus:ring-2 focus:ring-indigo-500 outline-none font-black text-slate-600 shadow-inner appearance-none"
              >
                {FOCUS_OPTIONS.map(opt => <option key={opt} value={opt}>{opt}</option>)}
              </select>
              <button disabled={loading} className="bg-indigo-600 hover:bg-indigo-700 disabled:bg-slate-200 text-white px-10 py-6 rounded-3xl font-black shadow-lg flex items-center justify-center gap-3">
                {loading ? <Loader2 className="animate-spin" size={24} /> : 'ANALYZE'}
              </button>
            </form>
          </div>
        </section>

        {error && (
          <div className="max-w-2xl mx-auto mb-10 bg-red-50 border border-red-200 p-8 rounded-[2rem] text-red-700 flex items-start gap-4 animate-in slide-in-from-top-4">
            <AlertTriangle className="shrink-0" />
            <div>
              <h4 className="font-black text-sm uppercase tracking-tight">Authorization Error</h4>
              <p className="text-sm font-medium">{error}</p>
            </div>
          </div>
        )}

        {loading && (
          <div className="py-32 text-center">
            <div className="w-16 h-16 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin mx-auto mb-6"></div>
            <h3 className="text-xl font-black text-slate-800">Compiling Ecological Markers...</h3>
          </div>
        )}

        {result && !loading && (
          <div className="space-y-12 animate-in fade-in slide-in-from-bottom-8">
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-6">
              {[
                { label: "Regional Est.", val: result.estimatedTotalHaplotypes, icon: Target },
                { label: "Global Est.", val: result.estimatedGlobalHaplotypes, icon: Globe },
                { label: "Drift (π)", val: result.nucleotideDiversity.toFixed(4), icon: Scale },
                { label: "Insect Data", val: "Integrated", icon: Bug }
              ].map((stat, i) => (
                <div key={i} className="bg-white p-8 rounded-[2rem] border border-slate-200 shadow-sm">
                  <p className="text-[10px] text-slate-400 font-black uppercase tracking-widest flex items-center gap-2 mb-3">
                    <stat.icon size={12} /> {stat.label}
                  </p>
                  <p className="text-3xl font-black tracking-tight text-slate-900">{stat.val}</p>
                </div>
              ))}
            </div>

            <StrainMap data={result.haplotypes} />
            <NetworkGraph data={result.haplotypes} />

            <div className="grid lg:grid-cols-3 gap-10">
              <div className="lg:col-span-2">
                <div className="bg-white p-12 rounded-[3rem] border border-slate-200 relative shadow-sm">
                  <div className="flex items-center gap-4 mb-8 pb-6 border-b border-slate-100">
                    <FileText className="text-indigo-600" />
                    <h3 className="text-2xl font-black uppercase tracking-tight text-slate-900">Research Dossier</h3>
                  </div>
                  <div className="text-slate-700 leading-relaxed font-medium">
                    <p className="mb-10 text-lg text-slate-800 border-l-4 border-indigo-200 pl-6 py-2">{result.dossier}</p>
                    <div className="mt-10 border-t border-slate-100 pt-8">
                      <h4 className="text-xs font-black uppercase tracking-[0.2em] text-slate-400 mb-8">Comprehensive Haplotype Profiles</h4>
                      <div className="space-y-12">
                        {result.haplotypes.map(h => (
                          <div key={h.id} className="bg-slate-50 p-10 rounded-[2.5rem] border border-slate-100 relative overflow-hidden group hover:bg-white hover:shadow-xl transition-all duration-500">
                            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
                              <div>
                                <span className="px-3 py-1 bg-indigo-600 text-white rounded-lg font-mono text-[11px] font-black">{h.id}</span>
                                <h5 className="text-xl font-black text-slate-900 mt-2">{h.region}</h5>
                              </div>
                              <div className="flex gap-2">
                                <span className="bg-white px-4 py-2 rounded-xl text-[10px] font-black border border-slate-200 shadow-sm">{h.similarity}% Similarity</span>
                              </div>
                            </div>
                            
                            <div className="grid md:grid-cols-2 gap-8">
                              <div className="space-y-6">
                                <div>
                                  <p className="text-[10px] font-black text-indigo-400 uppercase tracking-widest mb-2 flex items-center gap-2"><Target size={12}/> Host Association</p>
                                  <p className="text-sm font-bold text-slate-800 italic">{h.substrate}</p>
                                </div>
                                <div>
                                  <p className="text-[10px] font-black text-indigo-400 uppercase tracking-widest mb-2 flex items-center gap-2"><Sparkles size={12}/> Bio-Potential & Chemistry</p>
                                  <p className="text-xs text-slate-600 leading-relaxed">{h.chemistry}</p>
                                </div>
                                <div>
                                  <p className="text-[10px] font-black text-indigo-400 uppercase tracking-widest mb-2 flex items-center gap-2"><Layers size={12}/> Genomic Markers (SNPs)</p>
                                  <div className="flex flex-wrap gap-1.5">
                                    {h.snps.map((s, idx) => <span key={idx} className="px-2 py-1 bg-white border border-slate-200 text-indigo-600 rounded font-mono text-[10px] shadow-sm">{s}</span>)}
                                  </div>
                                </div>
                              </div>
                              
                              <div className="bg-indigo-50/50 p-6 rounded-3xl border border-indigo-100/50">
                                <p className="text-[10px] font-black text-indigo-600 uppercase tracking-widest mb-4 flex items-center gap-2">
                                  <Bug size={14}/> Entomological Context
                                </p>
                                <p className="text-xs text-indigo-900/80 leading-relaxed font-semibold italic">
                                  {h.insectAssociations}
                                </p>
                              </div>
                            </div>
                            <p className="text-[9px] text-slate-300 font-mono mt-8 uppercase tracking-tighter">Loc: {h.lat}, {h.lng}</p>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              
              <div className="space-y-8">
                <div className="bg-slate-900 p-10 rounded-[2.5rem] text-white shadow-2xl relative overflow-hidden group">
                   <Bug className="absolute bottom-0 right-0 text-white/5 -mb-6 -mr-6 group-hover:scale-110 transition-transform duration-700" size={180} />
                  <h3 className="font-black text-2xl mb-2 tracking-tight">Export Findings</h3>
                  <button onClick={handleExportDossier} className="w-full bg-indigo-600 hover:bg-indigo-500 py-5 rounded-2xl font-black flex items-center justify-center gap-3 transition-all">
                    <Download size={22} /> DOWNLOAD DATA v2.5
                  </button>
                </div>

                <div className="bg-white p-10 rounded-[2.5rem] border border-slate-200 shadow-sm">
                  <h4 className="font-black text-[10px] uppercase tracking-widest text-slate-400 mb-8 flex items-center gap-2"><Link size={14} className="text-indigo-400" /> Evidence Grounding</h4>
                  <div className="space-y-5">
                    {result.sources.map((s, i) => (
                      <a key={i} href={s.uri} target="_blank" className="group block p-5 rounded-2xl bg-slate-50 hover:bg-indigo-50 border border-slate-100 transition-all">
                        <p className="font-black text-slate-800 text-sm mb-1 group-hover:text-indigo-700 line-clamp-1">{s.title}</p>
                        <p className="text-slate-400 group-hover:text-indigo-400 truncate font-mono text-[10px] flex items-center gap-1.5"><Globe size={10} /> {new URL(s.uri).hostname}</p>
                      </a>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </main>
      <footer className="bg-white border-t border-slate-200 py-12 mt-20">
        <div className="max-w-7xl mx-auto px-6 text-center">
          <p className="text-[10px] font-black uppercase tracking-[0.3em] text-slate-400">Mycological Genomics Protocol {APP_VERSION}</p>
        </div>
      </footer>
    </div>
  );
}
