import React, { useState, useEffect, useMemo } from 'react';
import { performMycoAnalysis } from './services/geminiService';
import { AnalysisResult, Haplotype } from './types';
import { StrainMap } from './components/StrainMap';
import { NetworkGraph } from './components/NetworkGraph';
import { 
  Dna, Search, Loader2, AlertCircle, Download, Target, Globe, FileText, Link, Scale, Activity, ChevronDown, Sparkles, Key, LogOut, Info, Shield, ExternalLink, HelpCircle, ArrowRight, AlertTriangle, CheckCircle2, ChevronRight, Zap, RefreshCw, Layers, Bug, Map as MapIcon, TreeDeciduous, ListFilter
} from 'lucide-react';

const FOCUS_OPTIONS = ["National Survey", "Pacific Northwest (PNW)", "Appalachian Mountains", "Northeast Deciduous", "Southeast Coastal Plain", "Rocky Mountains / Alpine", "California Floristic", "Boreal Forest / Taiga"];
const APP_VERSION = "v4.1";

export default function App() {
  const [species, setSpecies] = useState('');
  const [focusArea, setFocusArea] = useState(FOCUS_OPTIONS[0]);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  // Derived data for the Variant Matrix
  const uniqueSnps = useMemo(() => {
    if (!result) return [];
    const snpSet = new Set<string>();
    result.haplotypes.forEach(h => h.snps.forEach(s => snpSet.add(s)));
    return Array.from(snpSet).sort();
  }, [result]);

  const handleSearch = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!species.trim()) return;

    setLoading(true);
    setError(null);
    try {
      const data = await performMycoAnalysis(species, focusArea);
      setResult(data);
    } catch (err: any) {
      setError(err.message || "An unexpected error occurred during genomic analysis.");
    } finally {
      setLoading(false);
    }
  };

  const formatHaplotypeData = (haplotypes: Haplotype[]) => {
    return haplotypes.map(h => {
      return `ID: ${h.id}
Region: ${h.region}
Similarity: ${h.similarity}%
Host Association: ${h.substrate}
Chemistry: ${h.chemistry}
Insect Associations: ${h.insectAssociations}
SNPs: ${h.snps.join(', ')}
Coordinates: [${h.lat}, ${h.lng}]
`;
    }).join('\n');
  };

  const handleExportDossier = () => {
    if (!result) return;
    const formattedHaplotypes = formatHaplotypeData(result.haplotypes);
    const fullContent = `
MYCOSTRAIN EXPLORER: GENOMIC & ENTOMOLOGICAL REPORT
====================================================
Species: ${result.speciesName}
Focus Area: ${result.focusArea}
Nucleotide Diversity (π): ${result.nucleotideDiversity}
Estimated Regional Haplotypes: ${result.estimatedTotalHaplotypes}
Estimated Global Haplotypes: ${result.estimatedGlobalHaplotypes}

RESEARCH SUMMARY
----------------
${result.dossier}

HAPLOTYPE DATA
--------------
${formattedHaplotypes}
----------------
Generated by MycoStrain Explorer ${APP_VERSION}
    `.trim();

    const blob = new Blob([fullContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `MycoStrain_${result.speciesName.replace(/\s/g, '_')}_Dossier_v4.1.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col font-sans">
      <nav className="bg-white/80 backdrop-blur-md border-b border-slate-200 sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="bg-indigo-600 p-2.5 rounded-xl text-white shadow-lg"><Dna size={24} /></div>
            <div className="flex flex-col">
              <div className="flex items-center gap-2">
                <h1 className="text-xl font-black text-slate-900 tracking-tight leading-none">MycoStrain <span className="text-indigo-600">Explorer</span></h1>
                <span className="px-2 py-0.5 bg-slate-100 border border-slate-200 text-slate-500 rounded-md text-[9px] font-black uppercase tracking-tighter">{APP_VERSION}</span>
              </div>
              <p className="text-[9px] font-black text-slate-400 uppercase tracking-[0.2em] mt-1">Bioinformatics & Entomology</p>
            </div>
          </div>
          {/* System Secure control removed as it was cosmetic only */}
        </div>
      </nav>

      <main className="max-w-7xl mx-auto px-6 py-10 flex-grow w-full">
        <section className="mb-12 text-center max-w-4xl mx-auto">
          <h2 className="text-5xl font-black text-slate-900 mb-4 tracking-tighter">Genomic & Entomological Modeling</h2>
          <p className="text-slate-500 text-lg font-medium leading-relaxed mb-10">Advanced variant alignment and steel-silhouette mapping for high-precision mycological research.</p>
          <div className="bg-white p-4 rounded-[2.5rem] shadow-2xl border border-slate-200/60 ring-8 ring-slate-100/50">
            <form onSubmit={handleSearch} className="flex flex-col lg:flex-row gap-4">
              <input 
                type="text" 
                value={species} 
                onChange={(e) => setSpecies(e.target.value)} 
                placeholder="Scientific Name (e.g. Cordyceps militaris)" 
                className="flex-[1.5] pl-10 pr-6 py-6 rounded-3xl bg-slate-50 border-none focus:ring-2 focus:ring-indigo-500 outline-none font-bold text-slate-800 shadow-inner" 
              />
              <select 
                value={focusArea} 
                onChange={(e) => setFocusArea(e.target.value)} 
                className="flex-1 px-10 py-6 rounded-3xl bg-slate-50 border-none focus:ring-2 focus:ring-indigo-500 outline-none font-black text-slate-600 shadow-inner appearance-none"
              >
                {FOCUS_OPTIONS.map(opt => <option key={opt} value={opt}>{opt}</option>)}
              </select>
              <button disabled={loading} className="bg-indigo-600 hover:bg-indigo-700 disabled:bg-slate-200 text-white px-10 py-6 rounded-3xl font-black shadow-lg flex items-center justify-center gap-3 transition-all active:scale-95">
                {loading ? <Loader2 className="animate-spin" size={24} /> : 'ANALYZE'}
              </button>
            </form>
          </div>
        </section>

        {error && (
          <div className="max-w-2xl mx-auto mb-10 bg-red-50 border border-red-200 p-8 rounded-[2rem] text-red-700 flex items-start gap-4 animate-in slide-in-from-top-4">
            <AlertTriangle className="shrink-0" />
            <div>
              <h4 className="font-black text-sm uppercase tracking-tight">System Notification</h4>
              <p className="text-sm font-medium">{error}</p>
            </div>
          </div>
        )}

        {loading && (
          <div className="py-32 text-center">
            <div className="w-16 h-16 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin mx-auto mb-6"></div>
            <h3 className="text-xl font-black text-slate-800 tracking-tight">Synthesizing Genomic Matrix...</h3>
          </div>
        )}

        {result && !loading && (
          <div className="space-y-12 animate-in fade-in slide-in-from-bottom-8">
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-6">
              {[
                { label: "Regional Est.", val: result.estimatedTotalHaplotypes, icon: Target },
                { label: "Global Est.", val: result.estimatedGlobalHaplotypes, icon: Globe },
                { label: "Drift (π)", val: result.nucleotideDiversity.toFixed(4), icon: Scale },
                { label: "Protocol", val: "v4.1", icon: Shield }
              ].map((stat, i) => (
                <div key={i} className="bg-white p-8 rounded-[2rem] border border-slate-200 shadow-sm">
                  <p className="text-[10px] text-slate-400 font-black uppercase tracking-widest flex items-center gap-2 mb-3">
                    <stat.icon size={12} /> {stat.label}
                  </p>
                  <p className="text-3xl font-black tracking-tight text-slate-900">{stat.val}</p>
                </div>
              ))}
            </div>

            <StrainMap data={result.haplotypes} speciesName={result.speciesName} />
            
            {/* NEW: GENOMIC VARIANT ALIGNMENT MATRIX */}
            <div className="bg-slate-900 p-10 rounded-[3rem] shadow-2xl border border-slate-800 overflow-hidden">
              <div className="flex items-center justify-between mb-8">
                <div>
                  <h3 className="text-2xl font-black text-white flex items-center gap-3">
                    <ListFilter className="text-indigo-400" /> Regional Variant Alignment Matrix
                  </h3>
                  <p className="text-[10px] font-black text-slate-500 uppercase tracking-widest mt-1 italic">Mutation Profile of 12 Haplotypes vs All Unique SNPs</p>
                </div>
                <div className="flex items-center gap-2 px-4 py-2 bg-slate-800 rounded-xl border border-slate-700 text-[10px] font-black text-slate-400 uppercase tracking-widest">
                  <Sparkles size={12} className="text-indigo-400" /> {uniqueSnps.length} Unique markers
                </div>
              </div>
              
              <div className="overflow-x-auto custom-scrollbar pb-4">
                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr>
                      <th className="p-4 bg-slate-800 text-[10px] font-black text-slate-400 uppercase tracking-widest border border-slate-700 sticky left-0 z-20 min-w-[180px]">Haplotype ID</th>
                      {uniqueSnps.map(snp => (
                        <th key={snp} className="p-4 bg-slate-800 text-[10px] font-mono font-black text-indigo-300 uppercase tracking-widest border border-slate-700 min-w-[100px] text-center">{snp}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {result.haplotypes.map((h) => (
                      <tr key={h.id} className="hover:bg-slate-800/50 transition-colors">
                        <td className="p-4 bg-slate-900 text-xs font-black text-white border border-slate-800 sticky left-0 z-10 shadow-xl">
                          <div className="flex items-center gap-2">
                            <span className="w-2 h-2 rounded-full" style={{ background: `hsl(${parseInt(h.id.replace(/\D/g,'')) * 30}, 70%, 50%)` }}></span>
                            {h.id}
                          </div>
                        </td>
                        {uniqueSnps.map(snp => {
                          const hasSnp = h.snps.includes(snp);
                          return (
                            <td key={snp} className="p-4 border border-slate-800 text-center">
                              {hasSnp ? (
                                <div className="inline-flex items-center justify-center w-6 h-6 rounded-full bg-indigo-500/20 border border-indigo-500/50 shadow-[0_0_10px_rgba(99,102,241,0.3)]">
                                  <div className="w-2 h-2 rounded-full bg-indigo-400"></div>
                                </div>
                              ) : (
                                <div className="w-1.5 h-1.5 rounded-full bg-slate-700 mx-auto opacity-30"></div>
                              )}
                            </td>
                          );
                        })}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            <NetworkGraph data={result.haplotypes} />

            <div className="grid lg:grid-cols-3 gap-10">
              <div className="lg:col-span-2">
                <div className="bg-white p-12 rounded-[3rem] border border-slate-200 relative shadow-sm overflow-hidden">
                  <div className="flex items-center gap-4 mb-8 pb-6 border-b border-slate-100">
                    <FileText className="text-indigo-600" />
                    <h3 className="text-2xl font-black uppercase tracking-tight text-slate-900">Research Dossier</h3>
                  </div>
                  <div className="text-slate-700 leading-relaxed font-medium">
                    <p className="mb-10 text-lg text-slate-800 border-l-4 border-indigo-200 pl-6 py-2 bg-indigo-50/20 rounded-r-2xl">{result.dossier}</p>
                    <div className="mt-10 border-t border-slate-100 pt-8">
                      <h4 className="text-xs font-black uppercase tracking-[0.2em] text-slate-400 mb-8">Regional Profiles</h4>
                      <div className="space-y-12">
                        {result.haplotypes.map(h => (
                          <div key={h.id} className="bg-slate-50 p-10 rounded-[2.5rem] border border-slate-100 relative overflow-hidden group hover:bg-white hover:shadow-xl transition-all duration-500">
                            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
                              <div>
                                <span className="px-3 py-1 bg-indigo-600 text-white rounded-lg font-mono text-[11px] font-black">{h.id}</span>
                                <h5 className="text-xl font-black text-slate-900 mt-2">{h.region}</h5>
                              </div>
                              <div className="flex gap-2">
                                <span className="bg-white px-4 py-2 rounded-xl text-[10px] font-black border border-slate-200 shadow-sm">{h.similarity}% Drift</span>
                              </div>
                            </div>
                            
                            <div className="grid md:grid-cols-2 gap-8">
                              <div className="space-y-6">
                                <div className="bg-indigo-50 p-6 rounded-2xl border border-indigo-100">
                                  <p className="text-[10px] font-black text-indigo-600 uppercase tracking-widest mb-2 flex items-center gap-2"><TreeDeciduous size={12}/> Host Association & Niche</p>
                                  <p className="text-sm font-black text-slate-800 italic">{h.substrate}</p>
                                </div>
                                <div>
                                  <p className="text-[10px] font-black text-indigo-400 uppercase tracking-widest mb-2 flex items-center gap-2"><Sparkles size={12}/> Genetic Markers</p>
                                  <p className="text-xs text-slate-600 leading-relaxed font-mono">{h.snps.join(', ')}</p>
                                </div>
                              </div>
                              
                              <div className="bg-slate-900 p-8 rounded-3xl border border-slate-800 relative">
                                <p className="text-[10px] font-black text-indigo-400 uppercase tracking-widest mb-4 flex items-center gap-2">
                                  <Bug size={14}/> Entomological Partner
                                </p>
                                <p className="text-xs text-white leading-relaxed font-semibold italic opacity-90">
                                  {h.insectAssociations}
                                </p>
                              </div>
                            </div>
                            <p className="text-[9px] text-slate-300 font-mono mt-8 uppercase tracking-tighter border-t border-slate-100 pt-4 flex justify-between">
                                <span>COORD: {h.lat.toFixed(5)}, {h.lng.toFixed(5)}</span>
                                <span>PROTOCOL: MYCO-V4.1</span>
                            </p>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              
              <div className="space-y-8">
                <div className="bg-slate-900 p-10 rounded-[2.5rem] text-white shadow-2xl relative overflow-hidden group">
                   <Bug className="absolute bottom-0 right-0 text-white/5 -mb-6 -mr-6 group-hover:scale-110 transition-transform duration-700" size={180} />
                  <h3 className="font-black text-2xl mb-2 tracking-tight">Export Findings</h3>
                  <button onClick={handleExportDossier} className="w-full bg-indigo-600 hover:bg-indigo-500 py-5 rounded-2xl font-black flex items-center justify-center gap-3 transition-all active:scale-95">
                    <Download size={22} /> DOWNLOAD DATA v4.1
                  </button>
                </div>

                <div className="bg-white p-10 rounded-[2.5rem] border border-slate-200 shadow-sm">
                  <h4 className="font-black text-[10px] uppercase tracking-widest text-slate-400 mb-8 flex items-center gap-2"><Link size={14} className="text-indigo-400" /> Evidence Grounding</h4>
                  <div className="space-y-5">
                    {result.sources.map((s, i) => (
                      <a key={i} href={s.uri} target="_blank" rel="noopener noreferrer" className="group block p-5 rounded-2xl bg-slate-50 hover:bg-indigo-50 border border-slate-100 transition-all">
                        <p className="font-black text-slate-800 text-sm mb-1 group-hover:text-indigo-700 line-clamp-1">{s.title}</p>
                        <p className="text-slate-400 group-hover:text-indigo-400 truncate font-mono text-[10px] flex items-center gap-1.5"><Globe size={10} /> {new URL(s.uri).hostname}</p>
                      </a>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </main>
      <footer className="bg-white border-t border-slate-200 py-12 mt-20">
        <div className="max-w-7xl mx-auto px-6 text-center">
          <p className="text-[10px] font-black uppercase tracking-[0.3em] text-slate-400">Mycological Genomics Protocol {APP_VERSION}</p>
        </div>
      </footer>
    </div>
  );
}
